config/routes.rb
Dmap::Engine.routes.draw do
  
  resources :categories

  get 'get_all_tags', to: 'posts#get_all_tags'
  get 'tags/:tag', to: 'posts#index', as: :tag

  resources :posts
  get 'personal_posts', to: 'posts#personal', as: :personal_posts
  get 'favorites', to: 'posts#favorites', as: :favorites
  get 'add_to_favorites/:id/:kind', to: 'posts#add_to_favorites', as: :add_to_favorites

  root :to => 'posts#index'

end

app/models/dmap/category.rb
module Dmap
  class Category < ActiveRecord::Base
    
    has_many :posts

    attr_accessible :name
    
  end
end

app/models/dmap/favorite.rb
module Dmap
  class Favorite < ActiveRecord::Base
    
    belongs_to :post
    belongs_to :user, :polymorphic => true
    
    attr_accessible :post_id, :user_id, :user_type

  end
end

app/models/dmap/post.rb
module Dmap
  class Post < ActiveRecord::Base
  
  	extend FriendlyId
  	friendly_id :title, use: [:slugged, :history]
    
    belongs_to :category
    belongs_to :user, :polymorphic => true
    
    attr_accessible :active, :description, :description_short, :published_at, :slug, :state, :title
    attr_accessible :category_id, :user_id, :user_type, :tag_list

	acts_as_taggable

	validates :title, :description_short, :description, :presence => true

	before_save :check_published
	after_save :reindex_posts

	searchable :auto_index => true, :auto_remove => true do
		integer :id
		text :title, :boost => 5.0, :stored => true
		text :description_short, :boost => 2.0, :stored => true
		text :description, :stored => true

		text :post_contents do
		  post_contents.map(&:content)
		end

		text :languages do
		  languages.map(&:title)
		end

		text :post_tags do
		  tag_list.map { |t| t }.join(', ')
		end

		string :tag_list, :multiple => true, :stored => true

		time :created_at
		string :publish_month 
	end

	def publish_month
		created_at.strftime("%B")
	end

	def post_tags
		Post.tagged_with(params[:tag])
	end

	def self.recommended
		all
	end

	def reindex_posts
		Post.solr_reindex
	end

	def self.last_ones
		order("id DESC").limit(6)
	end

	def similar_posts
		search_str = tag_list.collect{ |i| i[0] }.join(" ")

		search = Post.search do
		  keywords search_str, :minimum_match => 3
		  without(:id, [self.id])
		  paginate :per_page => 5, :page => 1
		end

		search.results
	end 

  end
end

app/controllers/dmap/application_controller.rb
module Dmap
  class ApplicationController < ActionController::Base
  end
end

app/controllers/dmap/categories_controller.rb
require_dependency "dmap/application_controller"

module Dmap
  class CategoriesController < ApplicationController
    # GET /categories
    # GET /categories.json
    def index
      @categories = Category.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @categories }
      end
    end
  
    # GET /categories/1
    # GET /categories/1.json
    def show
      @category = Category.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @category }
      end
    end
  
    # GET /categories/new
    # GET /categories/new.json
    def new
      @category = Category.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @category }
      end
    end
  
    # GET /categories/1/edit
    def edit
      @category = Category.find(params[:id])
    end
  
    # POST /categories
    # POST /categories.json
    def create
      @category = Category.new(params[:category])
  
      respond_to do |format|
        if @category.save
          format.html { redirect_to @category, notice: 'Category was successfully created.' }
          format.json { render json: @category, status: :created, location: @category }
        else
          format.html { render action: "new" }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PUT /categories/1
    # PUT /categories/1.json
    def update
      @category = Category.find(params[:id])
  
      respond_to do |format|
        if @category.update_attributes(params[:category])
          format.html { redirect_to @category, notice: 'Category was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /categories/1
    # DELETE /categories/1.json
    def destroy
      @category = Category.find(params[:id])
      @category.destroy
  
      respond_to do |format|
        format.html { redirect_to categories_url }
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/dmap/posts_controller.rb
require_dependency "dmap/application_controller"

module Dmap
  class PostsController < ApplicationController

    before_filter :authenticate_user!, except: [:index, :show]
    before_filter :set_global_vars

    def set_global_vars
      @per_page = 2
    end

    def personal
      @posts = current_user.posts.paginate(:per_page => @per_page, :page => params[:page] || 1)

      respond_to do |format|
        format.html  { render action: "index" }
      end
    end

    def favorites
      @posts = current_user.favorite_posts.paginate(:per_page => @per_page, :page => params[:page] || 1)

      respond_to do |format|
        format.html  { render action: "index" }
      end
    end

    def index
      @title = ""
      per_page = @per_page

      if !params[:tag].nil? && params[:tag] != ""
        @title = "En " + params[:tag]
      end

      if !params[:search].nil? && params[:search] != ""
        if @title == ""
          @title = "Con: " + params[:search]
        else
          @title += " con: " + params[:search]
        end
      end

      @search = Post.search do
        keywords params[:search], :minimum_match => 3
        #fulltext params[:search] do
        #  highlight :title, :description_short, :description
        #end
        
        facet :tag_list      
        if params[:tag].present?
          with(:tag_list, params[:tag])
        end

        paginate :per_page => per_page, :page => params[:page] || 1
      end

      #@posts = @search.hits
      @posts = @search.results

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @posts }
      end
    end

    def get_all_tags
      tags = Post.tag_counts_on(:tags).collect{ |item| item.name }

      respond_to do |format|
        format.json { render :json => tags }
      end
    end

    def show
      @post = Post.find(params[:id])
      @similar_posts = @post.similar_posts

      if request.path != post_path(@post)
        redirect_to @post, status: :moved_permanently
        return 
      end

      @title_page = "ADN - #{@post.title}"

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @post }
      end
    end

    def new
      @post = Post.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @post }
      end
    end

    def edit
      @post = Post.find(params[:id])
    end

    def create
      @post = Post.new(params[:post])
      @post.user_id = current_user.id

      respond_to do |format|
        if @post.save
          format.html { redirect_to @post, notice: 'El articulo ha sido creado.' }
          format.json { render json: @post, status: :created, location: @post }
        else
          format.html { render action: "new" }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      @post = Post.find(params[:id])

      respond_to do |format|
        if @post.update_attributes(params[:post])
          format.html { redirect_to @post, notice: 'El articulo ha sido actualizado.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @post = Post.find(params[:id])
      @post.destroy

      respond_to do |format|
        format.html { redirect_to posts_url }
        format.json { head :no_content }
      end
    end

    def add_to_favorites
      if user_signed_in?
        current_user.add_to_favorites(params[:id], params[:kind])
      end
    end

  end
end

app/helpers/dmap/application_helper.rb
module Dmap
  module ApplicationHelper
  end
end

app/helpers/dmap/categories_helper.rb
module Dmap
  module CategoriesHelper
  end
end

app/helpers/dmap/posts_helper.rb
module Dmap
  module PostsHelper
  end
end

app/views/dmap/categories/_form.html.erb
<%= simple_form_for @category, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                categories_path, :class => 'btn' %>
  </div>
<% end %>

app/views/dmap/categories/edit.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/dmap/categories/index.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.id, category_path(category) %></td>
        <td><%= category.name %></td>
        <td><%=l category.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_category_path(category), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      category_path(category),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_category_path,
            :class => 'btn btn-primary' %>

app/views/dmap/categories/new.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/dmap/categories/show.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @category.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              categories_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_category_path(@category), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              category_path(@category),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/dmap/posts/_form.html.erb
<%= simple_form_for @post, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.association :category, label: "Categoria", :include_blank => false %>
  
  <%= f.input :title, label: "Titulo", input_html: {:class => "input-xlarge"} %>
  <%= f.input :description_short, label: "Descripcion", input_html: {:class => "input-xlarge"} %>

  <%= f.input :description, label: "Contenido",  :as => :ckeditor, :input_html => { :ckeditor => {:toolbar => 'MyToolbar'} } %> 

  <%= f.input :active, label: "Publico", as: :radio_buttons, collection: [['Si', true], ['No', false]], item_wrapper_class: 'inline' %>
  <%#= f.input :active, :as => :radio, :collection => [["Yes", 1], ["No", 0]], :checked => 1 %>
  
  <% f.input :tag_list, collection: Post.tag_counts_on(:tags), input_html: { multiple: true } %>
  <%= f.input :tag_list, label: "Tags", input_html: {:class => "input-xlarge"} %>

  <%= f.fields_for :post_contents do |builder| %>
    <%= render 'post_content_fields', f: builder %>
  <% end %>

  <%= link_to_add_fields("Agregar Snippet", f, :post_contents) %>

  <hr />
  
  <div class="form-actions">
    <%= f.button :submit, "Guardar", :class => 'btn-primary' %>
    <%= link_to "Cancelar", posts_path, :class => 'btn' %>
  </div>
<% end %>

app/views/dmap/posts/_post.html.erb
<div class="post_box">
	<div>
		<div class="container">
			<div class="row">
				<% if user_signed_in? %>
					<div class="span1" style="width:20px; margin-top:23px;">
						<%= render :partial => "favorite_box", :locals => {:id => post.id} %>
					</div>
				<% end %>

				<div class="span8">
					<h3>
						<%= link_to post.title, post_path(post) %>
					</h3>
				</div>
			</div>
		</div>
	</div>
	
	<p>
		<% if post.description_short.present? %>
			<%= post.description_short %>
			<% if can? :update, post %>
				<%= link_to "", edit_post_path(post), :class => 'icon-pencil' %>
			<% end %>
		<% else %>
			<% if can? :update, post %>
				<blockquote>
					<%= link_to "", edit_post_path(post), :class => 'icon-pencil' %>
				</blockquote>
			<% end %>
		<% end %>

		<div>
			<em>
				<%= render :partial => "date_element", :object => post  %>
			</em>
		</div>
	</p>
	
	<% if !post.tag_list.empty? %>
		<div>
			<span class="icon-tags"></span>
			<%= raw post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
		</div>
	<% end %>
	
	<hr />
</div>

app/views/dmap/posts/_post_content_fields.html.erb
<fieldset>
	<%= f.association :language, label: "Lenguaje", :include_blank => false, :input_html => { :class => "select_language" } %>
	<%= f.input :content, label: "Snippet", input_html: {:class => "input-xxlarge"} %>
	
	<% f.input :_destroy, as: :boolean, label: "Eliminar Snippet"  %>
  	
  	<%= f.hidden_field :_destroy %>
  	<%= link_to "Eliminar Snippet", '#', class: "remove_fields" %>
  	<br /><br />
</fieldset>

app/views/dmap/posts/_snippet.html.erb
<div>
	<strong><%= snippet.language.title %></strong>
	<%= raw Pygments.highlight(snippet.content, lexer: snippet.language.title.downcase) %>
</div>

app/views/dmap/posts/add_to_favorites.js.erb
<% if user_signed_in? %>
	$("#favorite_box<%= params[:id] %>").html("<%=j link_to_favorite params[:id] %>");
<% end %>

app/views/dmap/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1>Editar Articulo</h1>
</div>
<%= render :partial => 'form' %>

app/views/dmap/posts/index.html.erb
<% if @title != "" %>
	<h2><%= @title %></h2>
<% end %>

<div>
  <%= render :partial => "post", :collection => @posts %>
</div>

<div>
	<%= will_paginate @posts, :container => false, :params => { :search => params[:search], :tag => params[:tag] } %>
</div>

app/views/dmap/posts/new.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1>Nuevo Articulo</h1>
</div>
<%= render :partial => 'form' %>

app/views/dmap/posts/show.html.erb
<% second_hr = false %>

<div class="post_box">
  <div class="container">
    <div class="row">
      <% if user_signed_in? %>
        <div class="span1" style="width:20px; margin-top:24px;">
          <%= render :partial => "favorite_box", :locals => {:id => @post.id} %>
        </div>
      <% end %>

      <div class="span8">
        <h2><%= @post.title %></h2>
      </div>
    </div>
  </div>

  <hr />

  <% if @post.description.present? %>
    <% second_hr = true %>
    <div class="">
      <%= sanitize @post.description %>
    </div>
  <% end %>

  <% if !@post.post_contents.empty? %>
    <%= render :partial => "snippet", :collection => @post.post_contents %>
  <% end %>
  
  <% if !@post.tag_list.empty? %>
    <% second_hr = true %>
    <div>
      <span class="icon-tags"></span>
      <%= raw @post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
    </div>
  <% end %>

  <div>
    <em>
      <%= render :partial => "date_element", :object => @post  %>
    </em>
  </div>

  <br />
  <div class="container">
    <div class="row">
      <div class="span1">
        <div class="fb-like" data-send="false" data-layout="button_count" data-width="450" data-show-faces="false"></div>
      </div>

      <div class="span1">
        <a href="https://twitter.com/share" class="twitter-share-button" data-hashtags="neurock">Tweet</a>
      </div>

      <div class="span1">
        <div class="g-plusone" data-size="medium"></div>
      </div>
    </div>    
  </div>
</div>

<% if @similar_posts.length > 0 %>
  <div>
    <h3>Algunos articulos que te pueden interesar</h3>
    <ul>
      <% @similar_posts.each do |post| %>
        <li><%= link_to post.title, post_path(post) %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              posts_path, :class => 'btn'  %>

  <% if can? :update, @post %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_post_path(@post), :class => 'btn' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                post_path(@post),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '¿Seguro que quieres eliminar este articulo?')) },
                :class => 'btn btn-danger' %>
  <% end %>
</div>

<!-- Facebook -->
<div id="fb-root"></div>
<script>
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=197696870255015";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>

<!-- Twitter -->
<script>
  !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
</script>

<!-- Google +1 -->
<script type="text/javascript">
  window.___gcfg = {lang: 'es'};

  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>

app/views/layouts/dmap/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dmap</title>
  <%= stylesheet_link_tag    "dmap/application", :media => "all" %>
  <%= javascript_include_tag "dmap/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>